### ISSUE TITLE
Error after drag & drop of config items

### ISSUE THREAD

**Issue by fonol** [hgiesel/anki_stats_plus#1]
Hi, thanks for the nice add-on!

Steps to reproduce for me:
1. Open the add-on config dialog.
2. Drag some item in the list of any tab to another place (I accidentally did that).
3. Hit Ok

```
Anki 2.1.41 (92aaaf71) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-03 08:38:40

Caught exception:
Traceback (most recent call last):
  File "C:\Users\tom-k\AppData\Roaming\Anki2\addons21\1009670238\gui\settings.py", line 29, in accept
    self.ui.deckBrowser.exportData(),
  File "C:\Users\tom-k\AppData\Roaming\Anki2\addons21\1009670238\gui\graph_list.py", line 56, in exportData
    item.name(),
AttributeError: 'QListWidgetItem' object has no attribute 'name'
```

**Comment by hgiesel** [comment]
Thanks for the report. I've pushed an update. Dragging the items is possible on purpose. It allows you to change the order how Graphs are displayed.

Please let me know if you encounter any more issues :)

**Comment by fonol** [comment]
Works perfectly fine now, thanks!
