### ISSUE TITLE
[Typo] Extra " on deck overview

### ISSUE THREAD

**Issue by kleinerpirat** [hgiesel/anki_stats_plus#6]
After `</script>`:

https://github.com/hgiesel/anki_stats_plus/blob/dd4aed341698f6577ade09acfe773bae442eec81/src/overview.py#L14

### Consequence:

![image](https://user-images.githubusercontent.com/62722460/122389038-cb5ba600-cf70-11eb-9b79-8d29020565c3.png)

**Comment by hgiesel** [comment]
Thanks a lot! I remember trying to look for it once, but couldn't find it back then!
